version: "3"

services:
  go:
    build: .
    working_dir: /got
    volumes:
      - type: bind
        source: ./got
        target: /got
    entrypoint: go
  dev:
    build: .
    stdin_open: true
    tty: true
    working_dir: /got
    volumes:
      - type: bind
        source: ./got
        target: /got
    command: sh
