version: "3"

services:
  go:
    build: .
    working_dir: /got
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./got
        target: /got
    entrypoint: go
  dev:
    build: .
    working_dir: /got
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./got
        target: /got
    command: sh
  got:
    build: .
    working_dir: /got
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./got
        target: /got
    entrypoint: ./got
